# Specifies what version of K8s you want to use
apiVersion: v1
# A service is used to expose your Deployment to the external access
kind: Service
metadata:
  name: intact-portal-search-interactions-service
spec:
  ports:
    - port: 31235
      protocol: TCP
      # The port which will be externally exposed. Must be in the range [30000, 32767].
      nodePort: 31245
      # The port on your Deployment which it will expose
      targetPort: 8082
  selector:
    # Selects the disease-portal-client Deployment to attach the Service to
    app: intact-portal-search-interactions
    # Tell K8s this wants to expose an external port
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intact-portal-search-interactions-deployment
spec:
  selector:
    matchLabels:
      app: intact-portal-search-interactions
  replicas: 1
  template:
    metadata:
      labels:
        app: intact-portal-search-interactions
    spec:
      containers:
        - name: intact-portal-search-interactions
          # Pull the latest image which contains interaction webservice and the built assets from EBI's dockerhub
          image: dockerhub.ebi.ac.uk/intact-ci/intact-portal-search-interactions:latest
          ports:
            # We are using interaction webservice config which serves on port 8082
            - containerPort: 8082
      imagePullSecrets:
        # Provided by GitLab, this allows K8s to connect to dockerhub.ebi.ac.uk
        - name: gitlab-registry
