image: docker:latest
services:
  - docker:dind
variables:
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:latest
  DOCKER_TLS_CERTDIR: ""
stages:
  - build-jar
  - build-docker-image
  - kubernetes-deploy

maven-build:
  image: maven:3-jdk-8
  stage: build-jar
  script: "mvn package -B -s settings.xml -Pip-solr-indexing-hx"
  after_script:
    - "mkdir /builds/intact-ci/intact-portal-search-interactions/target/"
    - "cp /builds/intact-ci/intact-portal-search-interactions/intact-search-interactions-ws/target/intact-search-interactions-ws-1.0.6-SNAPSHOT.jar /builds/intact-ci/intact-portal-search-interactions/target/"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: build-docker-image
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker --version
    - echo ${CONTAINER_IMAGE}
  script:
    - docker build -t ${CONTAINER_IMAGE} --no-cache .
    - docker image ls
    - docker push ${CONTAINER_IMAGE}
    - docker rmi ${CONTAINER_IMAGE}
    - docker logout "$CI_REGISTRY"

kubernetes-staging-deploy:
  stage: kubernetes-deploy
  image: alpine
  script:
    - echo "Deploy to staging server"
  environment:
    name: Test
    url: https://hx-wp-webadmin-24.wp-k8s.ebi.ac.uk:30041
  when: manual

