logging.level.org.springframework.data.solr=DEBUG

springdoc.paths-to-exclude=/swagger-resources/**

main.ws.url=@ws.url@
vm.base.urls=@vm.urls@

springdoc.swagger-ui.url=@ws.url@/v3/api-docs
springdoc.swagger-ui.config-url=@ws.url@/v3/api-docs/swagger-config

server.upload.batch.file.path=${java.io.tmpdir}
server.max-http-header-size=10000000
server.servlet.context-path=/intact/ws/interaction
server.port=8082

spring.data.solr.host=@solr.server@
